### ISSUE TITLE
Docker Permission Issue

### ISSUE THREAD

**Issue by Dodgexander** [misterunknown/ifm#121]
#59 doesn't seem to work properly due to faux permissions.

Upon creating the docker container the permissions of your chosen mount by default are root and not set correctly.

To fix you have to manually add chown the contents within the container to apache.

It would be solved if there was some kind of environmental you could set in Docker upon container creation which alters the user permissions and adds user: apache to the www-data group.

Even better, if on creation the docker could take into consideration environmental for both user and group, that way you can run the entire process as a chosen user and directories too.

**Comment by misterunknown** [comment]
> #59 doesn't seem to work properly due to faux permissions.

Indeed. The original contributor of the Dockerfile intended to use the IFM docker container with a custom "root_dir" and bind-mounted his volumes into the docker container. This was a real-world use-case as he managed several wordpress container volumes with the IFM container.

> To fix you have to manually add chown the contents within the container to apache.

How exactly would you intend to use the IFM? As a simple demo, or with a mounted directory from the host?

> It would be solved if there was some kind of environmental you could set in Docker upon container creation which alters the user permissions and adds user: apache to the www-data group.
> 
> Even better, if on creation the docker could take into consideration environmental for both user and group, that way you can run the entire process as a chosen user and directories too.

That shouldn't be a problem. If you have any experience with docker files, you are welcome to create a pull request. I'm willing to fix that, but don't have as many time as I want to, to work on this project. I'll add this definitely to the TODO list.

Cheers,
Marco

**Comment by Dodgexander** [comment]
thanks!

I wish I did have experience with docker, it took me far too long to work out what the problem was to begin with!

**Comment by misterunknown** [comment]
I reworked the Dockerfile completely.

You can set a custom user by setting `IFM_DOCKER_UID` and `IFM_DOCKER_GID` (gid is optional) when starting the docker container.

Please let me know if that works for you.

**Comment by Dodgexander** [comment]
I have been testing your changes @misterunknown and they seem to work as intended.

The only drawback I can see with this approach (compared to other docker containers) is that the processes inside the container are running by default as user "apache".

Here are the permissions of my data folders:

>bash-4.3# ls -l
> total 16
> drwxr-xr-x    9 1000     1000          4096 Jan 14 05:43 downloads
> drwxr-xr-x    9 1000     1000          4096 Jan 14 05:41 media
> drwxr-xr-x    2 1000     1000          4096 Jan 14 05:41 uploads
> drwxr-xr-x    2 1000     1000          4096 Jan 14 05:41 user
> bash-4.3# ps aux
> PID   USER     TIME   COMMAND
>     1 root       0:00 httpd -DFOREGROUND
>   190 apache     0:00 httpd -DFOREGROUND
>   191 apache     0:00 httpd -DFOREGROUND
>   192 apache     0:00 httpd -DFOREGROUND
>   193 apache     0:00 httpd -DFOREGROUND
>   194 apache     0:00 httpd -DFOREGROUND
>   195 root       0:00 bash
>   201 root       0:00 ps aux

This means that you have to set `IFM_DOCKER_UID` also to UID: apache or at least set 'IFM_DOCKER_GID' to the same group as these running processes.

To the new user, none of this makes sense and it makes IFM unusable without manual changes.

Do you have any idea how to, or if its possible to change the user running these processes inside the container? If you knew, the best thing would be to take notice of your environmentals also when running these processes.

If not, perhaps by default the dockerfile should set `IFM_DOCKER_UID` as user:apache, or at least 'IFM_DOCKER_GID' to the same group as user apache within the container.

Does this make sense? Nontheless your current changes make it a lot easier to get everything working well, with no manual change needed other than setting your two enviromentals correct before creating the container.

Really appreciate your time!

**Comment by Dodgexander** [comment]
Okay, some further investigation has led to more problems.

By default on my system there is a user with a different name that shares the same UID as apache (33) in the container. The name of UID 33 on my system is www-data.

So setting the environmental to `IFM_DOCKER_UID=33` or `IFM_DOCKER_UID=www-data doesn't work.

The container expects you to be user apache with id 33.

When I try to set `IFM_DOCKER_UID=33` strangely in the container my own user account is used instead, perhaps explaining that you cannot mixmatch user id and user name.

**Comment by misterunknown** [comment]
Hm, if you use UID and GID 33, you shoudn't need to adjust them, as this is the default. However, I fixed the wrong creation of the user, so you can try again.

**Comment by Dodgexander** [comment]
This is my docker compose file:

>         image: digitalmobil/ifm
>         container_name: ifm
>         restart: unless-stopped
>         volumes:
>             - /mnt/data:/var/www/html/data
>         ports:
>             - '8990:80'
>         environment:
>             - IFM_AUTH=1
>             - IFM_API_CHMOD=1
>             - IFM_API_COPYMOVE=1
>             - IFM_API_CREATEDIR=1
>             - IFM_API_CREATEFILE=1
>             - IFM_API_EDIT=1
>             - IFM_API_DELETE=1
>             - IFM_API_DOWNLOAD=1
>             - IFM_API_EXTRACT=1
>             - IFM_API_UPLOAD=1
>             - IFM_API_REMOTEUPLOAD=1
>             - IFM_API_RENAME=1
>             - IFM_API_ZIPNLOAD=1
>             - IFM_GUI_SHOWLASTMODIFIED=1
>             - IFM_GUI_SHOWFILESIZE=1
>             - IFM_GUI_SHOWOWNER=1
>             - IFM_GUI_SHOWGROUP=1
>             - IFM_GUI_SHOWPERMISSIONS=1
>             - IFM_GUI_SHOWPATH=1
>             - IFM_GUI_CONTEXTMENU=1
>             - IFM_TIMEZONE="America/Detroit"
>             - IFM_DOCKER_UID=33
>             - IFM_DOCKER_GID=33

When I use bash in the container after this I get:

> bash-4.3# cd html/data
> bash-4.3# ls -l
> total 79
> -rw-r--r--    1 1000     1000         35070 Jan 14 02:22 4f79bd130e12f9c207ec3e73.nzb.queued
> drwxr-xr-x   10 1000     1000            11 Jan 14 07:36 downloads
> drwxr-xr-x    9 1000     1000             9 Jul 31 00:56 media
> drwxr-xr-x    2 1000     1000             2 Jan  2 07:34 uploads
> drwxr-xr-x    3 1000     1000             4 Dec 11 02:00 user
> bash-4.3# ps aux
> PID   USER     TIME   COMMAND
>     1 root       0:00 httpd -DFOREGROUND
>   190 apache     0:00 httpd -DFOREGROUND
>   191 apache     0:00 httpd -DFOREGROUND
>   192 apache     0:00 httpd -DFOREGROUND
>   193 apache     0:00 httpd -DFOREGROUND
>   194 apache     0:00 httpd -DFOREGROUND
>   195 root       0:00 bash
>   201 root       0:00 ps aux

According to the container, user apache is id 33

> bash-4.3# id apache
> uid=33(apache) gid=33(apache) groups=33(apache),33(apache),82(www-data)

But for some reason my container is always made with user id 1000 instead.

I'm sure its something stupid I am doing wrong?

**Comment by Dodgexander** [comment]
Some more info from:
`less /etc/passwd`
````
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
apache:x:33:33:Linux User,,,:/home/apache:/bin/false

**Comment by misterunknown** [comment]
> I'm sure its something stupid I am doing wrong?

Well, it seems that you use an very old docker container. You shouldn't use `digitalmobil/ifm`, but either `pinknet/ifm` (the official build), or build the container by yourself, with
```
docker build -t ifm .
```

**Comment by Dodgexander** [comment]
Omg! How did I miss I was using an older release? :/ so sorry for wasting your time!

This is what I have now (volume folder owner/group is still not set to 33). The process within the container is now successfully running as user 33, group 33 but my folders are not.

> /usr/local/share/webapps/ifm # ls -l www/html/data
> total 79
> -rwxrwxrwx    1 1000     1000         35070 Jan 14 02:22 4f79bd130e12f9c207ec3e73.nzb.queued
> drwxrwxrwx   10 1000     1000            11 Jan 14 07:36 downloads
> drwxrwxrwx    9 1000     1000             9 Jul 31 00:56 media
> drwxrwxrwx    2 1000     1000             2 Jan  2 07:34 uploads
> drwxrwxrwx    3 1000     1000             4 Dec 11 02:00 user
> /usr/local/share/webapps/ifm # ps
> PID   USER     TIME  COMMAND
>     1 root      0:00 {docker-startup.} /bin/sh /usr/local/bin/docker-startup.sh
>    13 www-data  0:04 /usr/local/bin/php -S 0:80 -t /usr/local/share/webapps/ifm
>    86 root      0:00 /bin/sh
>    92 root      0:00 ps

Here's my current config:

>     ifm:
>         image: pinknet/ifm:latest
>         container_name: ifm
>         restart: unless-stopped
>         volumes:
>             - /mnt/data:/var/www/html/data
>         ports:
>             - '8990:80'
>         environment:
>             - IFM_AUTH=1
>             - IFM_API_CHMOD=1
>             - IFM_API_COPYMOVE=1
>             - IFM_API_CREATEDIR=1
>             - IFM_API_CREATEFILE=1
>             - IFM_API_EDIT=1
>             - IFM_API_DELETE=1
>             - IFM_API_DOWNLOAD=1
>             - IFM_API_EXTRACT=1
>             - IFM_API_UPLOAD=1
>             - IFM_API_REMOTEUPLOAD=1
>             - IFM_API_RENAME=1
>             - IFM_API_ZIPNLOAD=1
>             - IFM_GUI_SHOWLASTMODIFIED=1
>             - IFM_GUI_SHOWFILESIZE=1
>             - IFM_GUI_SHOWOWNER=1
>             - IFM_GUI_SHOWGROUP=1
>             - IFM_GUI_SHOWPERMISSIONS=1
>             - IFM_GUI_SHOWPATH=1
>             - IFM_GUI_CONTEXTMENU=1
>             - IFM_TIMEZONE=America/Detroit
>             - IFM_DOCKER_UID=33
>             - IFM_DOCKER_GID=33

EDIT

I since changed too:
>             - IFM_DOCKER_UID=1000
>             - IFM_DOCKER_GID=1000

to match my username outside of docker and now I get:

> /var/www/html/data # ls -l
> total 79
> -rwxrwxrwx    1 www-data www-data     35070 Jan 14 02:22 4f79bd130e12f9c207ec3e73.nzb.queued
> drwxrwxrwx   10 www-data www-data        11 Jan 14 07:36 downloads
> drwxrwxrwx    9 www-data www-data         9 Jul 31 00:56 media
> drwxrwxrwx    2 www-data www-data         2 Jan  2 07:34 uploads
> drwxrwxrwx    3 www-data www-data         4 Dec 11 02:00 user
> /var/www/html/data # ps
> PID   USER     TIME  COMMAND
>     1 root      0:00 {docker-startup.} /bin/sh /usr/local/bin/docker-startup.sh
>    13 www-data  0:00 /usr/local/bin/php -S 0:80 -t /usr/local/share/webapps/ifm
>    14 root      0:00 /bin/sh
>    20 root      0:00 ps

Which **does** successfully change folder permissions, but not to what I set, but to www-data (33). I guess this is on purpose?

A bit strange, but it works now. So thankyou!

**Comment by misterunknown** [comment]
> volume folder owner/group is still not set to 33

Yes, this is intended. The container will _never ever_ change any UID/GID of mounted volumes – that would be really dangerous. The process in the container will always run with a user named `www-data`, which by default has UID/GID 33. If you mount a volume with different UID/GID, for example 1000:1000, then you can adjust the UID/GID of `www-data` within the container using the corresponding env variables. But that's the one and only purpose of these env variables.

Furthermore the `root_dir` of the IFM within the container is `/var/www`, not `/var/www/html/data` anymore.

**Comment by Dodgexander** [comment]
> > volume folder owner/group is still not set to 33
> 
> Yes, this is intended. The container will _never ever_ change any UID/GID of mounted volumes – that would be really dangerous. The process in the container will always run with a user named `www-data`, which by default has UID/GID 33. If you mount a volume with different UID/GID, for example 1000:1000, then you can adjust the UID/GID of `www-data` within the container using the corresponding env variables. But that's the one and only purpose of these env variables.
> 
> Furthermore the `root_dir` of the IFM within the container is `/var/www`, not `/var/www/html/data` anymore.

thank you for your wonderful creation and all your help!

**Comment by misterunknown** [comment]
You're welcome :)
